#!/usr/bin/env bash
# Wire the bdagstack Prometheus jobs and dashboard page into the running
# Netdata container. Idempotent — safe to re-run after edits.
#
# What it does:
#   1. Writes /etc/netdata/go.d/prometheus.conf with two jobs:
#        - bdag_chain_pool_local  (scrapes exporter:9198)
#        - bdag_node_native_local (scrapes node:6060)
#   2. Installs netdata-bdagstack.html into the netdata web root so users can
#      open http://localhost:19999/bdagstack.html.
#   3. Reloads Netdata.
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DASH_SRC="${ROOT_DIR}/config/netdata-bdagstack.html"
SERVICE="${SERVICE:-netdata}"

if ! docker compose ps --services --filter status=running 2>/dev/null | grep -qx "${SERVICE}"; then
  echo "${SERVICE} is not running. Start the stack first: make up" >&2
  exit 1
fi

read -r -d '' PROM_CONFIG <<'YAML' || true
# Generated by setup-netdata.sh — bdagStack scrape jobs.
jobs:
  - name: bdag_chain_pool_local
    url: http://exporter:9198/metrics
    update_every: 5
    selector:
      allow:
        - bdag_*

  - name: bdag_node_native_local
    url: http://node:6060/metrics
    update_every: 5
YAML

echo "Writing /etc/netdata/go.d/prometheus.conf inside ${SERVICE}"
docker compose exec -T "${SERVICE}" sh -c '
  set -e
  mkdir -p /etc/netdata/go.d
  cat >/etc/netdata/go.d/prometheus.conf
' <<<"${PROM_CONFIG}"

if [[ -f "${DASH_SRC}" ]]; then
  echo "Installing bdagstack.html into ${SERVICE} web root"
  docker compose exec -T "${SERVICE}" sh -c '
    set -e
    for d in /usr/share/netdata/web /opt/netdata/share/netdata/web; do
      if [ -d "$d" ]; then cp /dev/stdin "$d/bdagstack.html"; chmod 0644 "$d/bdagstack.html"; echo "Installed $d/bdagstack.html"; exit 0; fi
    done
    echo "WARNING: netdata web root not found inside container" >&2
  ' <"${DASH_SRC}"
else
  echo "Skipping dashboard install: ${DASH_SRC} not found"
fi

echo "Reloading ${SERVICE}"
docker compose restart "${SERVICE}"
echo "Done. Open http://localhost:${NETDATA_PORT:-19999}/bdagstack.html"
