#!/usr/bin/env bash
set -euo pipefail

root="${1:-.}"

fail() {
  printf 'release build validation failed: %s\n' "$*" >&2
  exit 1
}

need_file() {
  local file="$1"
  [[ -f "$root/$file" ]] || fail "missing $file"
}

need_grep() {
  local pattern="$1"
  local file="$2"
  grep -Eq "$pattern" "$root/$file" || fail "$file does not match required pattern: $pattern"
}

reject_grep() {
  local pattern="$1"
  local file="$2"
  [[ -f "$root/$file" ]] || return 0
  if grep -Eq "$pattern" "$root/$file"; then
    fail "$file still matches rejected pattern: $pattern"
  fi
}

reject_service_block_grep() {
  local service="$1"
  local pattern="$2"
  local file="$3"
  [[ -f "$root/$file" ]] || return 0
  if awk -v service="  ${service}:" -v pattern="$pattern" '
    $0 == service { in_block = 1; next }
    in_block && $0 ~ /^  [A-Za-z0-9_-]+:/ { in_block = 0 }
    in_block && $0 ~ pattern { found = 1 }
    END { exit found ? 0 : 1 }
  ' "$root/$file"; then
    fail "$file service $service still matches rejected pattern: $pattern"
  fi
}

need_file ".github/workflows/build.yml"
need_file "scripts/render-release-bootstrap.py"
need_file "scripts/release_bootstrap_static_test.py"
need_file "scripts/release_install_smoke.py"
need_file "scripts/verify-release-architecture.py"
need_file "scripts/check-release-archive.py"
need_file "scripts/validate-stack-defaults.py"
need_file "scripts/rebuild-test-stack-artifacts.sh"
need_file "scripts/sim-release.sh"
need_file "docker/entrypoint-collector.sh"
need_file "scripts/release/install.sh"
need_file "scripts/release/install.ps1"
need_file "scripts/release/install.cmd"
need_file "scripts/release/installers/install-unix-common.sh"
need_file "scripts/release/installers/install-windows.ps1"
need_file "ops/wait_for_node_sync.py"
need_file "README.md"
need_file "docs/glossary.md"
need_file "docs/adr/0001-pinned-bootstrap-runtime-payload-zips.md"
need_file "ops/tests/test_stack_naming_coherence.py"
need_file "ops/systemd/bdag-status-sampler.service"

PYTHONDONTWRITEBYTECODE=1 python3 "$root/scripts/validate-stack-defaults.py" "$root"

need_grep 'target: linux-amd64' ".github/workflows/build.yml"
need_grep 'target: linux-arm64' ".github/workflows/build.yml"
need_grep 'Checkout collector repo' ".github/workflows/build.yml"
need_grep 'BlockdagEngineering/collector' ".github/workflows/build.yml"
need_grep 'path: src/collector' ".github/workflows/build.yml"
need_grep 'find src/collector -type f -name collector[.]py' ".github/workflows/build.yml"
need_grep 'BlockdagEngineering/dashboard2' ".github/workflows/build.yml"
need_grep 'cmd/bdag/bdag.go' ".github/workflows/build.yml"
need_grep 'scripts/verify-release-architecture.py --target' ".github/workflows/build.yml"
need_grep 'scripts/check-release-archive.py' ".github/workflows/build.yml"
need_grep 'release_bootstrap_static_test.py' ".github/workflows/build.yml"
need_grep 'scripts/render-release-bootstrap.py' ".github/workflows/build.yml"
need_grep 'release_install_smoke.py' ".github/workflows/build.yml"
need_grep 'release_install_smoke.py' ".github/workflows/rc-hardening.yml"
need_grep 'release-payload.env' ".github/workflows/build.yml"
need_grep 'pool-stack-docker-\*\.zip' ".github/workflows/build.yml"
need_grep '^BDAG_CHAIN_DB_ARCHIVE_URL=' ".env.example"
need_grep 'normal-node-exports/.*/blockdag-normal-node-bootstrap-mainnet-20260623T080429Z-verified[.]tar[.]zst' ".env.example"
need_grep '^BDAG_CHAIN_DB_ARCHIVE_MIN_BYTES=1048576$' ".env.example"
need_grep '^BDAG_CHAIN_DB_IMPORT_BATCH_BYTES=16777216$' ".env.example"
need_grep '[.]tar[.]zst' ".env.example"
need_grep 'BDAG_CHAIN_DB_ARCHIVE_URL' "ops/release-install.sh"
reject_grep 'BDAG_CHAIN_DB_ARCHIVE_SHA256' ".env.example"
reject_grep 'BDAG_CHAIN_DB_ARCHIVE_SHA256' "ops/config/stack-defaults.env"
reject_grep 'BDAG_CHAIN_DB_ARCHIVE_SHA256' "ops/release-install.sh"
need_grep 'snap import --datadir' "ops/release-install.sh"
need_grep 'tar --zstd -xf' "ops/release-install.sh"
need_grep 'chain_db_archive_local_path' "ops/release-install.sh"
need_grep 'BDAG_RELEASE_INSTALL_CHAIN_DB_ONLY' "ops/release-install.sh"
need_grep 'Existing node chain data was found in \$node_dir/mainnet/BdagChain; skipping chain DB download.' "ops/release-install.sh"
need_grep 'ensure_node_datadir_bind_mount' "scripts/release/installers/install-unix-common.sh"
need_grep 'apply_chain_db_archive_env_overrides' "scripts/release/installers/install-unix-common.sh"
need_grep 'BDAG_RELEASE_INSTALL_CHAIN_DB_ONLY=1 bash ops/release-install.sh --chain-db-only' "scripts/release/installers/install-unix-common.sh"
need_grep 'docker compose up -d --no-build --pull never node' "scripts/release/installers/install-unix-common.sh"
need_grep 'python3 ops/wait_for_node_sync.py' "scripts/release/installers/install-unix-common.sh"
need_grep 'docker compose up -d --no-build --pull never pool-db pool collector dashboard' "scripts/release/installers/install-unix-common.sh"
reject_grep 'docker compose up -d --no-build --pull never postgres node dashboard' "scripts/release/installers/install-unix-common.sh"
need_grep '^BDAG_STACK_SERVICES=postgres,node,pool$' ".env.example"
need_grep 'BDAG_NODE_SERVICES: node' "docker-compose.yml"
need_grep 'NODE_RPC_URLS: .*http://node:38131' "docker-compose.yml"
need_grep '^BDAG_STATUS_SAMPLER_MAX_AGE_SECONDS=' ".env.example"
need_grep '^BDAG_STATUS_PAYLOAD_STALE_AFTER_SECONDS=' ".env.example"
need_grep '^POOL_GBT_MIN_INTERVAL_MS=' ".env.example"
need_grep 'pool_template_rpc_pressure' "scripts/mining-appliance-preflight.py"
need_grep 'ensure_stack_default_env_value BDAG_POOL_CONTAINER' "ops/install-dashboard.sh"
need_grep '^BDAG_DOCKER_BRIDGE_CIDRS=172.16.0.0/12$' ".env.example"
need_grep '^BDAG_ALLOW_DOCKER_BRIDGE_ASIC_IPS=0$' ".env.example"
reject_grep 'SNAPSHOT_PATH' ".env.example"
reject_grep 'SNAPSHOT_PATH' "docker-compose.yml"
reject_grep 'BDAG_SNAPSHOT_URL' ".env.example"
reject_grep 'BDAG_SNAPSHOT_URL' "docker-compose.yml"
reject_grep 'snap import' "dockerfile"
need_grep '^DASHBOARD_HOST_PORT=8088$' ".env.example"
need_grep '\$\{DASHBOARD_HOST_PORT:-8088\}:8088' "docker-compose.yml"
reject_grep '^[A-Z0-9_]*CONTEXT=\.\.' ".env.example"
need_grep '^COLLECTOR_SRC_CONTEXT=./collector$' ".env.example"
need_grep 'collector_src: \$\{COLLECTOR_SRC_CONTEXT:-\./collector\}' "docker-compose.yml"
need_grep 'dashboard_src: \$\{DASHBOARD_SRC_CONTEXT:-\.\}' "docker-compose.yml"
need_grep 'src/collector/ "\$\{ROOT\}/collector/"' ".github/workflows/build.yml"
need_grep 'cp "\$\{collector_entry\}" "\$\{ROOT\}/collector/collector[.]py"' ".github/workflows/build.yml"
need_grep 'Release zip is missing collector[.]py' ".github/workflows/build.yml"
need_grep 'FROM docker:27-cli AS ops-runtime' "dockerfile"
need_grep 'FROM ops-runtime AS collector' "dockerfile"
need_grep 'FROM ops-runtime AS watchdog' "dockerfile"
need_grep 'FROM ops-runtime AS sentinel' "dockerfile"
need_grep 'COPY --from=collector_src \. /src/collector' "dockerfile"
need_grep 'COPY --from=collector-source /src/collector /opt/collector' "dockerfile"
need_grep 'target: watchdog' "docker-compose.yml"
need_grep 'target: sentinel' "docker-compose.yml"
reject_service_block_grep 'watchdog' 'collector_src' "docker-compose.yml"
reject_service_block_grep 'sentinel' 'collector_src' "docker-compose.yml"
need_grep 'add_pythonpath_dir /opt/collector/ops' "docker/entrypoint-collector.sh"
need_grep 'add_pythonpath_dir "\$BDAG_PROJECT_ROOT/ops"' "docker/entrypoint-collector.sh"
need_grep 'PYTHONPATH="\$collector_pythonpath' "docker/entrypoint-collector.sh"
need_grep 'pool_ops[.]bdag_child_running_from_top = bdag_child_running_from_top' "docker/entrypoint-collector.sh"
need_grep 'executable_name == "rosetta" or executable_name[.]startswith\("qemu-"\)' "docker/entrypoint-collector.sh"
need_grep 'runpy[.]run_path\(sys[.]argv\[1\], run_name="__main__"\)' "docker/entrypoint-collector.sh"
need_grep '^app=/opt/collector/collector[.]py$' "docker/entrypoint-collector.sh"
reject_grep 'git clone --depth 1' "dockerfile"
reject_grep 'ARG COLLECTOR_REF' "dockerfile"
reject_grep 'COPY --from=collector_src \. /opt/collector' "dockerfile"
need_grep '^BOOTSTRAP_PEER_ADDRESSES=/ip4/13\.57\.132\.47/tcp/8150/p2p/16Uiu2HAmDynYpWjWmgVGf9qVWvDdLnJ3ybVgDmFexizR4zMereus$' ".env.example"
need_grep 'BOOTSTRAP_PEER_ADDRESSES: \$\{BOOTSTRAP_PEER_ADDRESSES:-\}' "docker-compose.yml"
need_grep '^addpeer=/ip4/13\.57\.132\.47/tcp/8150/p2p/16Uiu2HAmDynYpWjWmgVGf9qVWvDdLnJ3ybVgDmFexizR4zMereus$' "node.conf.example"
reject_grep '^addpeer=/ip4/52\.8\.80\.249/tcp/8150/p2p/' "node.conf.example"
reject_grep '^addpeer=/ip4/192\.168\.' "node.conf.example"
need_grep '^p2ptcpport=8150$' "node.conf.example"
need_grep '^profile=0\.0\.0\.0:1234$' "node.conf.example"
need_grep 'evmenv=.*--maxpeers 50 --port 30303' "node.conf.example"
need_grep 'COPY docker/node_metrics_exporter[.]py /usr/local/bin/node-metrics-exporter[.]py' "dockerfile"
need_grep 'python3-minimal' "dockerfile"
need_grep 'BDAG_NODE_METRICS_EXPORTER_ENABLED: \$\{BDAG_NODE_METRICS_EXPORTER_ENABLED:-1\}' "docker-compose.yml"
need_grep 'start_node_metrics_exporter' "docker/entrypoint-nodeworker.sh"
need_grep 'cp "\$TARGET_DIR/node[.]conf[.]example" "\$TARGET_DIR/node[.]conf"' "scripts/local-deploy-test-release.sh"
need_grep 'node_conf_bootstrap_peers "\$TARGET_DIR/node[.]conf"' "scripts/local-deploy-test-release.sh"
need_grep 'set_env_value "\$TARGET_DIR/[.]env" "BOOTSTRAP_PEER_ADDRESSES"' "scripts/local-deploy-test-release.sh"
reject_grep 'CURRENT_STACK/node[.]conf' "scripts/local-deploy-test-release.sh"
need_grep 'PAYLOAD_SOURCE="\$\{PAYLOAD_SOURCE:-/home/ben/repos/test-stack\}"' "scripts/local-test-release.sh"
need_grep 'TARGET_DIR="\$\{2:-/home/ben/repos/test-stack\}"' "scripts/local-deploy-test-release.sh"
need_grep 'CURRENT_STACK="\$\{CURRENT_STACK:-/home/ben/repos/test-stack\}"' "scripts/local-deploy-test-release.sh"
need_grep 'REPOS_DIR="\$\{REPOS_DIR:-\$\(cd "\$ROOT/\.\." && pwd\)\}"' "scripts/rebuild-test-stack-artifacts.sh"
need_grep 'TEST_STACK="\$\{TEST_STACK:-\$REPOS_DIR/test-stack\}"' "scripts/rebuild-test-stack-artifacts.sh"
need_grep 'build_node' "scripts/rebuild-test-stack-artifacts.sh"
need_grep 'build_pool' "scripts/rebuild-test-stack-artifacts.sh"
need_grep 'build_dashboard' "scripts/rebuild-test-stack-artifacts.sh"
need_grep 'sync_collector' "scripts/rebuild-test-stack-artifacts.sh"
need_grep 'rebuild-test-stack-artifacts[.]sh" all' "scripts/sim-release.sh"
need_grep 'local-test-release[.]sh" "\$VERSION"' "scripts/sim-release.sh"
need_grep 'local-deploy-test-release[.]sh" "\$ZIP_PATH" "\$TARGET_DIR"' "scripts/sim-release.sh"
need_grep 'source: \$TARGET_DIR/node-data' "scripts/sim-release.sh"
reject_grep '/home/ben/pool-stack-docker-local-test-linux-amd64' "scripts/local-deploy-test-release.sh"
reject_grep '/home/ben/pool-stack-docker-pool-v6[.]5[.]7-linux-amd64' "scripts/local-test-release.sh"
reject_grep '/home/ben/pool-stack-docker-pool-v6[.]5[.]7-linux-amd64' "scripts/local-deploy-test-release.sh"
need_grep 'bootstrapnode_arg_from_csv' "docker/entrypoint-nodeworker.sh"
need_grep 'BDAG_FASTSYNC_APPEND_BOOTSTRAPNODE' "docker/entrypoint-nodeworker.sh"
need_grep 'bootstrapnode=' "docker/entrypoint-nodeworker.sh"
need_grep 'pool-stack-docker-<tag>-linux-amd64\.zip' "README.md"
need_grep 'pool-stack-docker-<tag>-linux-arm64\.zip' "README.md"

need_grep 'release-payload.env' "scripts/release/installers/install-unix-common.sh"
need_grep 'release-payload.env' "scripts/release/installers/install-windows.ps1"
need_grep 'set_env_value .env DOCKER_PLATFORM "\$DOCKER_PLATFORM"' "scripts/release/installers/install-unix-common.sh"
need_grep 'Set-EnvValue .env DOCKER_PLATFORM \$dockerPlatform' "scripts/release/installers/install-windows.ps1"
need_grep 'python3 ops/wait_for_node_sync.py' "ops/release-install.sh"
need_grep 'Wait-ForNodeSync' "scripts/release/installers/install-windows.ps1"
need_grep 'ops\\wait_for_node_sync[.]py' "scripts/release/installers/install-windows.ps1"
need_grep 'Syncing graph state' "ops/wait_for_node_sync.py"
need_grep 'docker logs -f --tail' "ops/wait_for_node_sync.py"
need_grep 'docker_logs\(LOG_CONTAINER, lines=LOG_LINES\)' "ops/wait_for_node_sync.py"
need_grep 'Syncing graph state ETA' "p2p/synch/peersync.go"

reject_grep 'amd64 emulation' "scripts/release/installers/install-unix-common.sh"
reject_grep 'amd64 emulation' "scripts/release/installers/install-windows.ps1"
reject_grep 'build-pi5-arm64-release\.sh' ".github/workflows/build.yml"
reject_grep 'build-pi5-arm64-release\.sh' ".github/workflows/rc-hardening.yml"
reject_grep 'build-pi5-arm64-release\.sh' "README.md"
reject_grep 'build-pi5-arm64-release\.sh' "AGENTS.md"
reject_grep 'build-pi5-arm64-release\.sh' "docs/glossary.md"
reject_grep 'build-pi5-arm64-release\.sh' "docs/adr/0001-pinned-bootstrap-runtime-payload-zips.md"
reject_grep 'validate-pi5-restart-hardening\.sh' ".github/workflows/build.yml"
reject_grep 'validate-pi5-restart-hardening\.sh' ".github/workflows/rc-hardening.yml"

printf 'release build validation passed for %s\n' "$root"
