{
 "title": "BDAG Thermals",
 "tags": [
  "blockdag",
  "mining",
  "provisioned"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Max Thermal Zone",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "max(node_thermal_zone_temp)" }
   ]
  },
  {
   "title": "Thermal Zones",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    { "expr": "node_thermal_zone_temp", "legendFormat": "{{zone}}" }
   ]
  },
  {
   "title": "CPU Frequency",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "expr": "node_cpu_scaling_frequency_hertz",
     "legendFormat": "{{cpu}}"
    }
   ]
  }
 ]
}