#!/usr/bin/env bash
set -euo pipefail

ROOT="${BDAG_PROJECT_ROOT:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}"
P2P_PORTS="${BDAG_P2P_PORTS:-8151,8152}"
P2P_PROTOCOLS="${BDAG_P2P_PROTOCOLS:-tcp}"

warn() { printf 'WARNING: %s\n' "$*" >&2; }

env_value() {
  local key="$1"
  local default_value="${2:-}"
  local value=""
  if [[ -v "$key" ]]; then
    printf '%s\n' "${!key}"
    return
  fi
  if [[ -f "$ROOT/.env" ]]; then
    value="$(sed -n "s/^${key}=//p" "$ROOT/.env" | tail -n1 | tr -d '\r' || true)"
    value="${value%\"}"
    value="${value#\"}"
    value="${value%\'}"
    value="${value#\'}"
  fi
  if [[ -n "$value" ]]; then
    printf '%s\n' "$value"
  else
    printf '%s\n' "$default_value"
  fi
}

set_env_value() {
  local file="$1" key="$2" value="$3"
  touch "$file"
  if grep -qE "^${key}=" "$file"; then
    sed -i "s|^${key}=.*|${key}=${value}|" "$file"
  else
    printf '%s=%s\n' "$key" "$value" >> "$file"
  fi
}

need_sudo() {
  if [[ "$(id -u)" == "0" ]]; then
    "$@"
  else
    sudo "$@"
  fi
}

install_firewall() {
  if [[ ! -f "$ROOT/ops/allow-p2p-iptables.sh" || ! -f "$ROOT/ops/systemd/bdag-p2p-firewall.service" ]]; then
    warn "P2P firewall files are missing under $ROOT/ops"
    return 0
  fi
  need_sudo install -m 0755 "$ROOT/ops/allow-p2p-iptables.sh" /usr/local/sbin/bdag-allow-p2p-iptables
  need_sudo install -m 0644 "$ROOT/ops/systemd/bdag-p2p-firewall.service" /etc/systemd/system/bdag-p2p-firewall.service
  printf 'BDAG_P2P_PORTS=%s\nBDAG_P2P_PROTOCOLS=%s\n' "$P2P_PORTS" "$P2P_PROTOCOLS" | need_sudo tee /etc/default/bdag-p2p-firewall >/dev/null
  need_sudo systemctl daemon-reload
  need_sudo systemctl enable --now bdag-p2p-firewall.service
}

install_local_peer_timer() {
  if [[ ! -x "$ROOT/ops/update-local-peers.py" || ! -f "$ROOT/ops/systemd/user-bdag-local-peers.timer" ]]; then
    warn "Local peer discovery files are missing under $ROOT/ops"
    return 0
  fi
  local user_systemd_dir="${XDG_CONFIG_HOME:-$HOME/.config}/systemd/user"
  mkdir -p "$user_systemd_dir"
  cat > "$user_systemd_dir/bdag-local-peers.service" <<EOF
[Unit]
Description=BlockDAG local P2P peer discovery
After=default.target docker.service

[Service]
Type=oneshot
WorkingDirectory=$ROOT
Nice=15
IOSchedulingClass=best-effort
IOSchedulingPriority=7
CPUWeight=25
IOWeight=25
ExecStart=$ROOT/ops/update-local-peers.py --apply
EOF
  install -m 0644 "$ROOT/ops/systemd/user-bdag-local-peers.timer" "$user_systemd_dir/bdag-local-peers.timer"
  systemctl --user daemon-reload
  systemctl --user enable --now bdag-local-peers.timer
}

install_fastsnap_seed_timer() {
  if [[ "$(env_value BDAG_NODE_MODE single)" == "single" ]]; then
    warn "FastSnap archive seed timer is deprecated for single-node pools; raw datadir source sidecar will be considered instead"
    return 0
  fi
  if [[ "$(env_value BDAG_FASTSNAP_SEED_TIMER_ENABLED 1)" != "1" ]]; then
    warn "FastSnap seed timer install disabled by BDAG_FASTSNAP_SEED_TIMER_ENABLED"
    return 0
  fi
  if [[ ! -x "$ROOT/ops/build-fastsnap-seed.sh" || ! -f "$ROOT/ops/systemd/user-bdag-fastsnap-seed.service" || ! -f "$ROOT/ops/systemd/user-bdag-fastsnap-seed.timer" ]]; then
    warn "FastSnap seed service files are missing under $ROOT/ops"
    return 0
  fi

  local user_systemd_dir="${XDG_CONFIG_HOME:-$HOME/.config}/systemd/user"
  local user_config_dir="${XDG_CONFIG_HOME:-$HOME/.config}"
  local pool_api_port node1_metrics_port node2_metrics_port max_lag require_fresh

  pool_api_port="$(env_value POOL_API_PORT 9090)"
  node1_metrics_port="$(env_value BDAG_NODE1_METRICS_PORT 6061)"
  node2_metrics_port="$(env_value BDAG_NODE2_METRICS_PORT 6062)"
  max_lag="$(env_value BDAG_FASTSNAP_MAX_EXPORT_BACKEND_LAG 1000)"
  require_fresh="$(env_value BDAG_FASTSNAP_REQUIRE_EXPORT_BACKEND_FRESH 1)"

  mkdir -p "$user_systemd_dir" "$user_config_dir"
  cat > "$user_config_dir/bdag-fastsnap-seed.env" <<EOF
# Generated by ops/install-p2p-services.sh. Override here for this host.
BDAG_PROJECT_ROOT=$ROOT
BDAG_ENV_FILE=$ROOT/.env
BDAG_COMPOSE_FILE=$ROOT/docker-compose.yml
BDAG_POOL_ADMIN_URL=http://127.0.0.1:$pool_api_port
BDAG_FASTSNAP_REQUIRE_EXPORT_BACKEND_FRESH=$require_fresh
BDAG_FASTSNAP_MAX_EXPORT_BACKEND_LAG=$max_lag
BDAG_FASTSNAP_NODE_METRICS_URLS=node1=http://127.0.0.1:$node1_metrics_port/debug/metrics/prometheus,node2=http://127.0.0.1:$node2_metrics_port/debug/metrics/prometheus
EOF
  install -m 0644 "$ROOT/ops/systemd/user-bdag-fastsnap-seed.service" "$user_systemd_dir/bdag-fastsnap-seed.service"
  install -m 0644 "$ROOT/ops/systemd/user-bdag-fastsnap-seed.timer" "$user_systemd_dir/bdag-fastsnap-seed.timer"
  systemctl --user daemon-reload
  systemctl --user enable --now bdag-fastsnap-seed.timer
}

install_rawdatadir_source_timer() {
  local mode
  mode="$(env_value BDAG_RAWDATADIR_SOURCE_MODE auto)"
  if [[ "$mode" =~ ^(0|false|no|off|disabled)$ ]]; then
    warn "Raw datadir FastArtifact source disabled by BDAG_RAWDATADIR_SOURCE_MODE=$mode"
    return 0
  fi
  if [[ ! -x "$ROOT/ops/fastartifact_source_eligibility.py" || ! -x "$ROOT/ops/maintain-rawdatadir-sidecar.sh" || ! -x "$ROOT/ops/publish-rawdatadir-artifact.sh" ]]; then
    warn "Raw datadir source files are missing under $ROOT/ops"
    return 0
  fi

  local user_systemd_dir="${XDG_CONFIG_HOME:-$HOME/.config}/systemd/user"
  local user_config_dir="${XDG_CONFIG_HOME:-$HOME/.config}"
  local network active_service source_dir sidecar_dir artifact_base

  network="$(env_value BDAG_FASTSNAP_NETWORK mainnet)"
  active_service="$(env_value BDAG_NODE_SERVICES bdag-miner-node-1)"
  active_service="${active_service%%,*}"
  case "$active_service" in
    bdag-miner-node-1|node1) source_dir="$(env_value BDAG_NODE1_DATA_DIR ./data/node1)/$network" ;;
    bdag-miner-node-2|node2) source_dir="$(env_value BDAG_NODE2_DATA_DIR ./data/node2)/$network" ;;
    *) source_dir="$(env_value BDAG_NODE_DATA_DIR ./data/node)/$network" ;;
  esac
  sidecar_dir="$(env_value BDAG_RAWDATADIR_SIDECAR_DIR ./data-restore/rawdatadir-sidecar/$network)"
  artifact_base="$(env_value BDAG_RAWDATADIR_ARTIFACT_BASE ./data-restore/rawdatadir)"

  mkdir -p "$user_systemd_dir" "$user_config_dir"
  cat > "$user_config_dir/bdag-rawdatadir-sidecar.env" <<EOF
# Generated by ops/install-p2p-services.sh. Source serving remains fail-closed
# when eligibility detects USB/removable storage, low disk, or high pressure.
BDAG_PROJECT_ROOT=$ROOT
BDAG_ENV_FILE=$ROOT/.env
BDAG_COMPOSE_FILE=$ROOT/docker-compose.yml
BDAG_RAWDATADIR_SOURCE_MODE=$mode
BDAG_RAWDATADIR_NETWORK=$network
BDAG_RAWDATADIR_SINGLE_NODE_SERVICE=$active_service
BDAG_RAWDATADIR_SIDECAR_SOURCE=$source_dir
BDAG_RAWDATADIR_SIDECAR_DIR=$sidecar_dir
BDAG_RAWDATADIR_ARTIFACT_BASE=$artifact_base
BDAG_RAWDATADIR_REQUIRE_SIGNED=$(env_value BDAG_RAWDATADIR_REQUIRE_SIGNED 1)
BDAG_RAWDATADIR_MAX_EXPORT_BACKEND_LAG=$(env_value BDAG_RAWDATADIR_MAX_EXPORT_BACKEND_LAG 10000)
BDAG_RAWDATADIR_SINGLE_NODE_FINALIZE=$(env_value BDAG_RAWDATADIR_SINGLE_NODE_FINALIZE 0)
BDAG_FASTSYNC_ARTIFACT_SIGNING_KEY_ID=$(env_value BDAG_FASTSYNC_ARTIFACT_SIGNING_KEY_ID "")
BDAG_FASTSYNC_ARTIFACT_SIGNING_KEY_HEX=$(env_value BDAG_FASTSYNC_ARTIFACT_SIGNING_KEY_HEX "")
EOF

  if "$ROOT/ops/fastartifact_source_eligibility.py" --status-file "$ROOT/ops/runtime/rawdatadir-source-status.json" >/dev/null; then
    set_env_value "$ROOT/.env" BDAG_RAWDATADIR_SOURCE_MODE "$mode"
    set_env_value "$ROOT/.env" BDAG_RAWDATADIR_ARTIFACT_BASE "$artifact_base"
    set_env_value "$ROOT/.env" BDAG_FASTSYNC_ARTIFACT_DIRECTORY "/fastartifact/rawdatadir/current"
    set_env_value "$ROOT/.env" BDAG_FASTSYNC_ARTIFACT_MANIFEST "/fastartifact/rawdatadir/current/manifest.json"
  else
    warn "Raw datadir source sidecar is not eligible on this host; status written to ops/runtime/rawdatadir-source-status.json"
  fi

  install -m 0644 "$ROOT/ops/systemd/user-bdag-rawdatadir-sidecar.service" "$user_systemd_dir/bdag-rawdatadir-sidecar.service"
  install -m 0644 "$ROOT/ops/systemd/user-bdag-rawdatadir-sidecar.timer" "$user_systemd_dir/bdag-rawdatadir-sidecar.timer"
  install -m 0644 "$ROOT/ops/systemd/user-bdag-rawdatadir-source.service" "$user_systemd_dir/bdag-rawdatadir-source.service"
  install -m 0644 "$ROOT/ops/systemd/user-bdag-rawdatadir-source.timer" "$user_systemd_dir/bdag-rawdatadir-source.timer"
  systemctl --user daemon-reload
  systemctl --user enable --now bdag-rawdatadir-sidecar.timer
  systemctl --user enable --now bdag-rawdatadir-source.timer
}

install_mining_host_tuning() {
  if [[ ! -x "$ROOT/ops/apply-mining-host-tuning.sh" || ! -f "$ROOT/ops/systemd/bdag-mining-host-tuning.service" || ! -f "$ROOT/ops/systemd/bdag-mining-host-tuning.timer" ]]; then
    warn "Mining host tuning files are missing under $ROOT/ops"
    return 0
  fi
  need_sudo install -m 0755 "$ROOT/ops/apply-mining-host-tuning.sh" /usr/local/sbin/bdag-apply-mining-host-tuning
  need_sudo install -m 0644 "$ROOT/ops/systemd/bdag-mining-host-tuning.service" /etc/systemd/system/bdag-mining-host-tuning.service
  need_sudo install -m 0644 "$ROOT/ops/systemd/bdag-mining-host-tuning.timer" /etc/systemd/system/bdag-mining-host-tuning.timer
  # The installed script runs from /usr/local/sbin under systemd, so persist
  # the release root explicitly. This lets active/passive tuning read the pool
  # metrics/env and prioritize the currently selected mining-template lane.
  printf 'BDAG_PROJECT_ROOT=%s\n' "$ROOT" | need_sudo tee /etc/default/bdag-mining-host-tuning >/dev/null
  need_sudo systemctl daemon-reload
  need_sudo systemctl enable --now bdag-mining-host-tuning.service
  need_sudo systemctl enable --now bdag-mining-host-tuning.timer
}

install_firewall
install_local_peer_timer
install_fastsnap_seed_timer
install_rawdatadir_source_timer
install_mining_host_tuning
