#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'USAGE'
Install the BlockDAG dashboard/watchdog as user-level systemd services.

Usage:
  ops/install-dashboard.sh [options]

Options:
  --name NAME          Service prefix. Default: bdag
  --bind ADDRESS      Dashboard bind address. Default: 127.0.0.1
  --port PORT         Dashboard port. Default: 8088
  --runtime-dir DIR   Runtime state/log directory. Default: ops/runtime
  --env-file FILE     Service environment file. Default: RUNTIME_DIR/ops.env
  --no-watchdog       Install only the dashboard service
  --no-sync-coordinator
                      Do not install the large-catch-up node sync coordinator
  --no-guards         Do not install sentinel, P2P, peer, chain, or snapshot guards
  --no-start          Write units but do not enable/start services
  -h, --help          Show this help

Examples:
  ops/install-dashboard.sh
  ops/install-dashboard.sh --name pool2 --port 8090 --runtime-dir /var/lib/bdag-pool2
USAGE
}

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
INSTANCE="bdag"
BIND="${BDAG_DASHBOARD_BIND:-127.0.0.1}"
PORT="${BDAG_DASHBOARD_PORT:-8088}"
RUNTIME_DIR="${BDAG_RUNTIME_DIR:-}"
ENV_FILE=""
INSTALL_WATCHDOG=1
INSTALL_SYNC_COORDINATOR=1
INSTALL_GUARDS=1
START_SERVICES=1
RUNTIME_SET=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    --name)
      INSTANCE="${2:?--name requires a value}"
      shift 2
      ;;
    --bind)
      BIND="${2:?--bind requires a value}"
      shift 2
      ;;
    --port)
      PORT="${2:?--port requires a value}"
      shift 2
      ;;
    --runtime-dir)
      RUNTIME_DIR="${2:?--runtime-dir requires a value}"
      RUNTIME_SET=1
      shift 2
      ;;
    --env-file)
      ENV_FILE="${2:?--env-file requires a value}"
      shift 2
      ;;
    --no-watchdog)
      INSTALL_WATCHDOG=0
      INSTALL_SYNC_COORDINATOR=0
      INSTALL_GUARDS=0
      shift
      ;;
    --no-sync-coordinator)
      INSTALL_SYNC_COORDINATOR=0
      shift
      ;;
    --no-guards)
      INSTALL_GUARDS=0
      shift
      ;;
    --no-start)
      START_SERVICES=0
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown option: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

INSTANCE="$(printf '%s' "$INSTANCE" | tr -c 'A-Za-z0-9_.-' '-')"
if [[ -z "$INSTANCE" ]]; then
  INSTANCE="bdag"
fi

if [[ -z "$RUNTIME_DIR" ]]; then
  if [[ "$INSTANCE" == "bdag" || "$RUNTIME_SET" -eq 1 ]]; then
    RUNTIME_DIR="$PROJECT_ROOT/ops/runtime"
  else
    RUNTIME_DIR="$PROJECT_ROOT/ops/runtime-$INSTANCE"
  fi
fi
if [[ -z "$ENV_FILE" ]]; then
  ENV_FILE="$RUNTIME_DIR/ops.env"
fi

mkdir -p "$RUNTIME_DIR/logs" "$(dirname "$ENV_FILE")" "$HOME/.config/systemd/user"

if [[ ! -f "$ENV_FILE" ]]; then
  cat > "$ENV_FILE" <<EOF
# Generated by ops/install-dashboard.sh. Edit this file for this pool instance.
BDAG_PROJECT_ROOT=$PROJECT_ROOT
BDAG_RUNTIME_DIR=$RUNTIME_DIR
BDAG_POOL_ENV_FILE=$PROJECT_ROOT/asic-pool/.env
BDAG_DASHBOARD_BIND=$BIND
BDAG_DASHBOARD_PORT=$PORT
BDAG_DASHBOARD_REQUIRE_TOKEN=auto

BDAG_POOL_CONTAINER=asic-pool
BDAG_POOL_DB_CONTAINER=pool-db
BDAG_POOL_DB_USER=test
BDAG_POOL_DB_NAME=pool
BDAG_NODE_MODE=single
BDAG_NODE_SERVICES=bdag-miner-node-2
BDAG_STACK_SERVICES=pool-db,bdag-miner-node-2,rpc-failover,asic-pool
BDAG_ENABLE_NODE_MINING=0
BDAG_FASTSYNC_PREPROCESS_WORKERS=1
BDAG_SHARED_STATUS_CACHE_ENABLED=1
BDAG_SHARED_STATUS_CACHE_SECONDS=3.0
BDAG_HOST_PROFILE=auto
BDAG_ADAPTIVE_CONCURRENCY_ENABLED=1
BDAG_ADAPTIVE_IOWAIT_WARN_PERCENT=25
BDAG_ADAPTIVE_IO_SOME_AVG10_WARN=20.0
BDAG_ADAPTIVE_CPU_SOME_AVG10_WARN=80.0
BDAG_ADAPTIVE_CHAIN_RPC_WARN_MS=1000
BDAG_GLOBAL_RPC_WORKERS=24
BDAG_MINER_SCAN_WORKERS=64
BDAG_MINER_HASHRATE_PROBE_WORKERS=8
BDAG_BACKGROUND_MAINTENANCE_BACKOFF_ENABLED=1
BDAG_BACKGROUND_MAINTENANCE_SYNC_BACKOFF_BLOCKS=0
BDAG_BACKGROUND_MAINTENANCE_IOWAIT_WARN_PERCENT=25
BDAG_BACKGROUND_MAINTENANCE_IO_SOME_AVG10_WARN=20.0
BDAG_BACKGROUND_MAINTENANCE_CPU_SOME_AVG10_WARN=80.0
BDAG_BACKGROUND_MAINTENANCE_CHAIN_RPC_WARN_MS=1000
BDAG_GLOBAL_HISTORY_COMPACT_MULTIPLIER=2
BDAG_ENTRYPOINT_CHOWN_MODE=needed
BDAG_ENABLE_AUTOMATIC_CLEAN_RESTORE=0
BDAG_BOOT_REPAIR_DIRTY_POLICY=start
BDAG_BOOT_REPAIR_CRITICAL_POLICY=restart
BDAG_INCIDENT_REPORT_ENABLED=0
BDAG_INCIDENT_REPORT_REPO=

# Optional overrides:
# BDAG_MINING_ADDRESS=0x0000000000000000000000000000000000000000
# BDAG_POOL_HOST=192.168.1.10
# BDAG_POOL_URL=stratum+tcp://192.168.1.10:3334
# BDAG_MINER_SCAN_TARGET=192.168.1.0/24
# DOCKER_HOST=ssh://pool-admin@192.168.1.10
# CMC_PRO_API_KEY=
EOF
  chmod 0600 "$ENV_FILE"
fi

ensure_env_value() {
  local key="$1" value="$2"
  if ! grep -q "^${key}=" "$ENV_FILE"; then
    printf '%s=%s\n' "$key" "$value" >> "$ENV_FILE"
  fi
}

ensure_env_value BDAG_PROJECT_ROOT "$PROJECT_ROOT"
ensure_env_value BDAG_RUNTIME_DIR "$RUNTIME_DIR"
ensure_env_value BDAG_POOL_ENV_FILE "$PROJECT_ROOT/asic-pool/.env"
ensure_env_value BDAG_NODE_MODE single
ensure_env_value BDAG_NODE_SERVICES bdag-miner-node-2
ensure_env_value BDAG_STACK_SERVICES "pool-db,bdag-miner-node-2,rpc-failover,asic-pool"
ensure_env_value BDAG_ENABLE_NODE_MINING 0
ensure_env_value BDAG_FASTSYNC_PREPROCESS_WORKERS 1
ensure_env_value BDAG_SHARED_STATUS_CACHE_ENABLED 1
ensure_env_value BDAG_SHARED_STATUS_CACHE_SECONDS 3.0
ensure_env_value BDAG_HOST_PROFILE auto
ensure_env_value BDAG_ADAPTIVE_CONCURRENCY_ENABLED 1
ensure_env_value BDAG_ADAPTIVE_IOWAIT_WARN_PERCENT 25
ensure_env_value BDAG_ADAPTIVE_IO_SOME_AVG10_WARN 20.0
ensure_env_value BDAG_ADAPTIVE_CPU_SOME_AVG10_WARN 80.0
ensure_env_value BDAG_ADAPTIVE_CHAIN_RPC_WARN_MS 1000
ensure_env_value BDAG_GLOBAL_RPC_WORKERS 24
ensure_env_value BDAG_MINER_SCAN_WORKERS 64
ensure_env_value BDAG_MINER_HASHRATE_PROBE_WORKERS 8
ensure_env_value BDAG_BACKGROUND_MAINTENANCE_BACKOFF_ENABLED 1
ensure_env_value BDAG_BACKGROUND_MAINTENANCE_SYNC_BACKOFF_BLOCKS 0
ensure_env_value BDAG_BACKGROUND_MAINTENANCE_IOWAIT_WARN_PERCENT 25
ensure_env_value BDAG_BACKGROUND_MAINTENANCE_IO_SOME_AVG10_WARN 20.0
ensure_env_value BDAG_BACKGROUND_MAINTENANCE_CPU_SOME_AVG10_WARN 80.0
ensure_env_value BDAG_BACKGROUND_MAINTENANCE_CHAIN_RPC_WARN_MS 1000
ensure_env_value BDAG_GLOBAL_HISTORY_COMPACT_MULTIPLIER 2
ensure_env_value BDAG_ENTRYPOINT_CHOWN_MODE needed
ensure_env_value BDAG_ENABLE_AUTOMATIC_CLEAN_RESTORE 0
ensure_env_value BDAG_BOOT_REPAIR_DIRTY_POLICY start
ensure_env_value BDAG_BOOT_REPAIR_CRITICAL_POLICY restart
ensure_env_value BDAG_INCIDENT_REPORT_ENABLED 0
ensure_env_value BDAG_INCIDENT_REPORT_REPO ""

DASHBOARD_SERVICE="$HOME/.config/systemd/user/${INSTANCE}-dashboard.service"
WATCHDOG_SERVICE="$HOME/.config/systemd/user/${INSTANCE}-watchdog.service"
BOOT_REPAIR_SERVICE="$HOME/.config/systemd/user/${INSTANCE}-boot-repair.service"
SYNC_COORDINATOR_SERVICE="$HOME/.config/systemd/user/${INSTANCE}-sync-coordinator.service"
SYNC_COORDINATOR_TIMER="$HOME/.config/systemd/user/${INSTANCE}-sync-coordinator.timer"
STACK_SENTINEL_SERVICE="$HOME/.config/systemd/user/${INSTANCE}-stack-sentinel.service"
STACK_SENTINEL_TIMER="$HOME/.config/systemd/user/${INSTANCE}-stack-sentinel.timer"
NODE_CHILD_GUARD_SERVICE="$HOME/.config/systemd/user/${INSTANCE}-node-child-guard.service"
NODE_CHILD_GUARD_TIMER="$HOME/.config/systemd/user/${INSTANCE}-node-child-guard.timer"
P2P_GUARD_SERVICE="$HOME/.config/systemd/user/${INSTANCE}-p2p-guard.service"
LOCAL_PEERS_SERVICE="$HOME/.config/systemd/user/${INSTANCE}-local-peers.service"
LOCAL_PEERS_TIMER="$HOME/.config/systemd/user/${INSTANCE}-local-peers.timer"
CHAIN_RESTORE_GUARD_SERVICE="$HOME/.config/systemd/user/${INSTANCE}-chain-restore-guard.service"
CHAIN_RESTORE_GUARD_TIMER="$HOME/.config/systemd/user/${INSTANCE}-chain-restore-guard.timer"
CHAIN_PRESYNC_SERVICE="$HOME/.config/systemd/user/${INSTANCE}-chain-presync.service"
CHAIN_PRESYNC_TIMER="$HOME/.config/systemd/user/${INSTANCE}-chain-presync.timer"
HOURLY_SNAPSHOT_SERVICE="$HOME/.config/systemd/user/${INSTANCE}-hourly-snapshot.service"
HOURLY_SNAPSHOT_TIMER="$HOME/.config/systemd/user/${INSTANCE}-hourly-snapshot.timer"
INCIDENT_REPORTER_SERVICE="$HOME/.config/systemd/user/${INSTANCE}-incident-reporter.service"
INCIDENT_REPORTER_TIMER="$HOME/.config/systemd/user/${INSTANCE}-incident-reporter.timer"

cat > "$DASHBOARD_SERVICE" <<EOF
[Unit]
Description=BlockDAG pool operations dashboard ($INSTANCE)
After=${INSTANCE}-boot-repair.service default.target

[Service]
Type=simple
WorkingDirectory=$PROJECT_ROOT
Environment=BDAG_PROJECT_ROOT=$PROJECT_ROOT
Environment=BDAG_RUNTIME_DIR=$RUNTIME_DIR
Environment=BDAG_DASHBOARD_BIND=$BIND
Environment=BDAG_DASHBOARD_PORT=$PORT
EnvironmentFile=-$ENV_FILE
ExecStart=/usr/bin/env python3 $PROJECT_ROOT/ops/dashboard.py
Restart=always
RestartSec=5

[Install]
WantedBy=default.target
EOF

if [[ "$INSTALL_WATCHDOG" -eq 1 ]]; then
  cat > "$WATCHDOG_SERVICE" <<EOF
[Unit]
Description=BlockDAG pool watchdog and auto-repair worker ($INSTANCE)
After=${INSTANCE}-boot-repair.service default.target

[Service]
Type=simple
WorkingDirectory=$PROJECT_ROOT
Environment=BDAG_PROJECT_ROOT=$PROJECT_ROOT
Environment=BDAG_RUNTIME_DIR=$RUNTIME_DIR
Environment=BDAG_WATCHDOG_INTERVAL=30
Environment=BDAG_WATCHDOG_FAILURE_THRESHOLD=3
Environment=BDAG_CLEAN_RESTORE_COOLDOWN=1800
EnvironmentFile=-$ENV_FILE
ExecStartPre=/bin/sh -c 'i=0; while [ "\$i" -lt 60 ]; do docker info >/dev/null 2>&1 && exit 0; i=\$((i+1)); sleep 5; done; exit 1'
ExecStart=/usr/bin/env python3 $PROJECT_ROOT/ops/watchdog.py --loop
ExecStopPost=/bin/sh -c 'rm -f "\$BDAG_RUNTIME_DIR/dirty-shutdown.marker"'
Restart=always
RestartSec=10

[Install]
WantedBy=default.target
EOF
fi

if [[ "$INSTALL_SYNC_COORDINATOR" -eq 1 ]]; then
  cat > "$SYNC_COORDINATOR_SERVICE" <<EOF
[Unit]
Description=BlockDAG large catch-up sync coordinator ($INSTANCE)
After=default.target

[Service]
Type=oneshot
WorkingDirectory=$PROJECT_ROOT
Environment=BDAG_PROJECT_ROOT=$PROJECT_ROOT
Environment=BDAG_RUNTIME_DIR=$RUNTIME_DIR
Environment=BDAG_SYNC_COORDINATOR_FAR_BEHIND_BLOCKS=1000
Environment=BDAG_SYNC_COORDINATOR_FOLLOWER_LAG_BLOCKS=1000
Environment=BDAG_SYNC_COORDINATOR_LEADER_NEAR_TIP_BLOCKS=1000
Environment=BDAG_SYNC_COORDINATOR_SEED_NEAR_TIP_BLOCKS=5
Environment=BDAG_SYNC_COORDINATOR_LEADER_CPU_SHARES=8192
Environment=BDAG_SYNC_COORDINATOR_LEADER_BLKIO_WEIGHT=1000
Environment=BDAG_SYNC_COORDINATOR_FINAL_RSYNC_TIMEOUT_SECONDS=600
EnvironmentFile=-$ENV_FILE
Nice=10
IOSchedulingClass=best-effort
IOSchedulingPriority=7
CPUWeight=40
IOWeight=30
ExecStart=/usr/bin/env python3 $PROJECT_ROOT/ops/sync_coordinator.py --once --repair --pause-follower --seed-follower --resume-follower --allow-leader-stop
EOF

  cat > "$SYNC_COORDINATOR_TIMER" <<EOF
[Unit]
Description=Run BlockDAG sync coordinator during large catch-up ($INSTANCE)

[Timer]
OnBootSec=3min
OnUnitActiveSec=2min
AccuracySec=30s
Persistent=true
Unit=${INSTANCE}-sync-coordinator.service

[Install]
WantedBy=timers.target
EOF
fi

if [[ "$INSTALL_WATCHDOG" -eq 1 ]]; then
  cat > "$BOOT_REPAIR_SERVICE" <<EOF
[Unit]
Description=BlockDAG pool boot-time recovery ($INSTANCE)
After=default.target

[Service]
Type=oneshot
WorkingDirectory=$PROJECT_ROOT
Environment=BDAG_PROJECT_ROOT=$PROJECT_ROOT
Environment=BDAG_RUNTIME_DIR=$RUNTIME_DIR
Environment=BDAG_WATCHDOG_INTERVAL=60
Environment=BDAG_WATCHDOG_FAILURE_THRESHOLD=3
Environment=BDAG_CLEAN_RESTORE_COOLDOWN=1800
Environment=BDAG_ENABLE_AUTOMATIC_CLEAN_RESTORE=0
Environment=BDAG_BOOT_REPAIR_DIRTY_POLICY=start
Environment=BDAG_BOOT_REPAIR_CRITICAL_POLICY=restart
EnvironmentFile=-$ENV_FILE
ExecStartPre=/bin/sh -c 'i=0; while [ "\$i" -lt 60 ]; do docker info >/dev/null 2>&1 && exit 0; i=\$((i+1)); sleep 5; done; exit 1'
ExecStart=/usr/bin/env python3 $PROJECT_ROOT/ops/watchdog.py --boot-repair

[Install]
WantedBy=default.target
EOF
fi

if [[ "$INSTALL_GUARDS" -eq 1 ]]; then
  cat > "$STACK_SENTINEL_SERVICE" <<EOF
[Unit]
Description=BlockDAG mining stack last-resort sentinel ($INSTANCE)
After=default.target

[Service]
Type=oneshot
WorkingDirectory=$PROJECT_ROOT
Environment=BDAG_PROJECT_ROOT=$PROJECT_ROOT
Environment=BDAG_RUNTIME_DIR=$RUNTIME_DIR
Environment=BDAG_SENTINEL_USER_SERVICES=${INSTANCE}-dashboard.service,${INSTANCE}-watchdog.service,${INSTANCE}-node-child-guard.service,${INSTANCE}-p2p-guard.service
Environment=BDAG_SENTINEL_USER_TIMERS=${INSTANCE}-stack-sentinel.timer,${INSTANCE}-node-child-guard.timer,${INSTANCE}-sync-coordinator.timer,${INSTANCE}-chain-restore-guard.timer,${INSTANCE}-chain-presync.timer,${INSTANCE}-hourly-snapshot.timer,${INSTANCE}-local-peers.timer,${INSTANCE}-incident-reporter.timer
EnvironmentFile=-$ENV_FILE
ExecStart=/usr/bin/env python3 $PROJECT_ROOT/ops/stack_sentinel.py
Nice=10
IOSchedulingClass=idle
CPUWeight=15
IOWeight=10
EOF

  cat > "$STACK_SENTINEL_TIMER" <<EOF
[Unit]
Description=Run BlockDAG mining stack sentinel ($INSTANCE)

[Timer]
OnBootSec=2min
OnUnitActiveSec=60s
AccuracySec=15s
Persistent=true
RandomizedDelaySec=5s
Unit=${INSTANCE}-stack-sentinel.service

[Install]
WantedBy=timers.target
EOF

  cat > "$NODE_CHILD_GUARD_SERVICE" <<EOF
[Unit]
Description=BlockDAG node child process guard ($INSTANCE)
After=${INSTANCE}-dashboard.service default.target

[Service]
Type=oneshot
WorkingDirectory=$PROJECT_ROOT
Environment=BDAG_PROJECT_ROOT=$PROJECT_ROOT
Environment=BDAG_RUNTIME_DIR=$RUNTIME_DIR
EnvironmentFile=-$ENV_FILE
ExecStart=/usr/bin/env python3 ops/node_child_guard.py
EOF

  cat > "$NODE_CHILD_GUARD_TIMER" <<EOF
[Unit]
Description=Run BlockDAG node child guard periodically ($INSTANCE)

[Timer]
OnBootSec=90s
OnUnitActiveSec=60s
AccuracySec=15s
Persistent=true
Unit=${INSTANCE}-node-child-guard.service

[Install]
WantedBy=timers.target
EOF

  cat > "$P2P_GUARD_SERVICE" <<EOF
[Unit]
Description=BlockDAG P2P and mining network health guard ($INSTANCE)
After=${INSTANCE}-dashboard.service default.target

[Service]
Type=simple
WorkingDirectory=$PROJECT_ROOT
Environment=BDAG_PROJECT_ROOT=$PROJECT_ROOT
Environment=BDAG_RUNTIME_DIR=$RUNTIME_DIR
Environment=BDAG_P2P_GUARD_INTERVAL=300
Environment=BDAG_POOL_ACTIVITY_LOG_LINES=1200
EnvironmentFile=-$ENV_FILE
ExecStartPre=/bin/sh -c 'i=0; while [ "\$i" -lt 60 ]; do docker info >/dev/null 2>&1 && curl -fsS http://127.0.0.1:$PORT/api/status >/dev/null 2>&1 && exit 0; i=\$((i+1)); sleep 5; done; exit 1'
ExecStart=/usr/bin/env python3 $PROJECT_ROOT/ops/p2p_guard.py --loop
Restart=always
RestartSec=15
Nice=8
IOSchedulingClass=best-effort
IOSchedulingPriority=7
CPUWeight=30
IOWeight=30

[Install]
WantedBy=default.target
EOF

  cat > "$LOCAL_PEERS_SERVICE" <<EOF
[Unit]
Description=BlockDAG local P2P peer discovery ($INSTANCE)
After=default.target

[Service]
Type=oneshot
WorkingDirectory=$PROJECT_ROOT
Environment=BDAG_PROJECT_ROOT=$PROJECT_ROOT
Environment=BDAG_RUNTIME_DIR=$RUNTIME_DIR
EnvironmentFile=-$ENV_FILE
Nice=15
IOSchedulingClass=best-effort
IOSchedulingPriority=7
CPUWeight=25
IOWeight=25
ExecStart=/usr/bin/env python3 $PROJECT_ROOT/ops/update-local-peers.py --apply
EOF

  cat > "$LOCAL_PEERS_TIMER" <<EOF
[Unit]
Description=Refresh BlockDAG local P2P peer discovery ($INSTANCE)

[Timer]
OnBootSec=3min
OnUnitActiveSec=30min
Persistent=true
RandomizedDelaySec=5min
Unit=${INSTANCE}-local-peers.service

[Install]
WantedBy=timers.target
EOF

  cat > "$CHAIN_RESTORE_GUARD_SERVICE" <<EOF
[Unit]
Description=BlockDAG chain restore-point freshness guard ($INSTANCE)
After=default.target

[Service]
Type=oneshot
WorkingDirectory=$PROJECT_ROOT
Environment=BDAG_PROJECT_ROOT=$PROJECT_ROOT
Environment=BDAG_RUNTIME_DIR=$RUNTIME_DIR
EnvironmentFile=-$ENV_FILE
ExecStart=/usr/bin/env python3 $PROJECT_ROOT/ops/chain_restore_guard.py
Nice=19
IOSchedulingClass=idle
CPUWeight=10
IOWeight=10
EOF

  cat > "$CHAIN_RESTORE_GUARD_TIMER" <<EOF
[Unit]
Description=Run BlockDAG chain restore-point freshness guard ($INSTANCE)

[Timer]
OnBootSec=3min
OnUnitActiveSec=5min
AccuracySec=30s
Persistent=true
RandomizedDelaySec=20s
Unit=${INSTANCE}-chain-restore-guard.service

[Install]
WantedBy=timers.target
EOF

  cat > "$CHAIN_PRESYNC_SERVICE" <<EOF
[Unit]
Description=BlockDAG live chain pre-sync ($INSTANCE)
After=default.target

[Service]
Type=oneshot
WorkingDirectory=$PROJECT_ROOT
Environment=BDAG_PROJECT_ROOT=$PROJECT_ROOT
Environment=BDAG_PRESYNC_ONE_NODE=1
EnvironmentFile=-$ENV_FILE
Nice=19
IOSchedulingClass=idle
CPUWeight=10
IOWeight=10
ExecStart=$PROJECT_ROOT/ops/chain-presync.sh
EOF

  cat > "$CHAIN_PRESYNC_TIMER" <<EOF
[Unit]
Description=Run BlockDAG live chain pre-sync every two hours ($INSTANCE)

[Timer]
OnBootSec=10min
OnUnitActiveSec=2h
Persistent=true
RandomizedDelaySec=5min
Unit=${INSTANCE}-chain-presync.service

[Install]
WantedBy=timers.target
EOF

  cat > "$HOURLY_SNAPSHOT_SERVICE" <<EOF
[Unit]
Description=BlockDAG hourly chain snapshot ($INSTANCE)
After=${INSTANCE}-watchdog.service ${INSTANCE}-dashboard.service default.target

[Service]
Type=oneshot
WorkingDirectory=$PROJECT_ROOT
Environment=BDAG_PROJECT_ROOT=$PROJECT_ROOT
EnvironmentFile=-$ENV_FILE
Nice=19
IOSchedulingClass=idle
CPUWeight=10
IOWeight=10
ExecStart=$PROJECT_ROOT/ops/hourly-chain-snapshot.sh
EOF

  cat > "$HOURLY_SNAPSHOT_TIMER" <<EOF
[Unit]
Description=Run BlockDAG chain snapshot periodically ($INSTANCE)

[Timer]
OnCalendar=hourly
Persistent=true
RandomizedDelaySec=120
Unit=${INSTANCE}-hourly-snapshot.service

[Install]
WantedBy=timers.target
EOF

  cat > "$INCIDENT_REPORTER_SERVICE" <<EOF
[Unit]
Description=BlockDAG incident reporter ($INSTANCE)
After=${INSTANCE}-dashboard.service default.target

[Service]
Type=oneshot
WorkingDirectory=$PROJECT_ROOT
Environment=BDAG_PROJECT_ROOT=$PROJECT_ROOT
EnvironmentFile=-$ENV_FILE
Nice=10
IOSchedulingClass=best-effort
IOSchedulingPriority=6
ExecStart=/usr/bin/env python3 ops/incident_reporter.py
EOF

  cat > "$INCIDENT_REPORTER_TIMER" <<EOF
[Unit]
Description=Run BlockDAG incident reporter periodically ($INSTANCE)

[Timer]
OnBootSec=5min
OnUnitActiveSec=15min
AccuracySec=1min
Persistent=true
Unit=${INSTANCE}-incident-reporter.service

[Install]
WantedBy=timers.target
EOF
fi

systemctl --user daemon-reload
if [[ "$START_SERVICES" -eq 1 ]]; then
  if [[ "$INSTALL_WATCHDOG" -eq 1 ]]; then
    systemctl --user enable --now "${INSTANCE}-boot-repair.service"
  fi
  systemctl --user enable --now "${INSTANCE}-dashboard.service"
  if [[ "$INSTALL_WATCHDOG" -eq 1 ]]; then
    systemctl --user enable --now "${INSTANCE}-watchdog.service"
  fi
  if [[ "$INSTALL_SYNC_COORDINATOR" -eq 1 ]]; then
    systemctl --user enable --now "${INSTANCE}-sync-coordinator.timer"
  fi
  if [[ "$INSTALL_GUARDS" -eq 1 ]]; then
    systemctl --user enable --now "${INSTANCE}-stack-sentinel.timer"
    systemctl --user enable --now "${INSTANCE}-node-child-guard.timer"
    systemctl --user enable --now "${INSTANCE}-p2p-guard.service"
    systemctl --user enable --now "${INSTANCE}-local-peers.timer"
    systemctl --user enable --now "${INSTANCE}-chain-restore-guard.timer"
    systemctl --user enable --now "${INSTANCE}-chain-presync.timer"
    systemctl --user enable --now "${INSTANCE}-hourly-snapshot.timer"
    systemctl --user enable --now "${INSTANCE}-incident-reporter.timer"
  fi
fi

cat <<EOF
Installed:
  $DASHBOARD_SERVICE
  $ENV_FILE

Dashboard:
  http://$BIND:$PORT

Edit the environment file for pool-specific container names, wallet address,
miner scan target, Docker remote host, and repair commands.
EOF
if [[ "$INSTALL_WATCHDOG" -eq 1 ]]; then
  echo "  $BOOT_REPAIR_SERVICE"
  echo "  $WATCHDOG_SERVICE"
fi
if [[ "$INSTALL_SYNC_COORDINATOR" -eq 1 ]]; then
  echo "  $SYNC_COORDINATOR_SERVICE"
  echo "  $SYNC_COORDINATOR_TIMER"
fi
if [[ "$INSTALL_GUARDS" -eq 1 ]]; then
  echo "  $STACK_SENTINEL_SERVICE"
  echo "  $STACK_SENTINEL_TIMER"
  echo "  $NODE_CHILD_GUARD_SERVICE"
  echo "  $NODE_CHILD_GUARD_TIMER"
  echo "  $P2P_GUARD_SERVICE"
  echo "  $LOCAL_PEERS_SERVICE"
  echo "  $LOCAL_PEERS_TIMER"
  echo "  $CHAIN_RESTORE_GUARD_SERVICE"
  echo "  $CHAIN_RESTORE_GUARD_TIMER"
  echo "  $CHAIN_PRESYNC_SERVICE"
  echo "  $CHAIN_PRESYNC_TIMER"
  echo "  $HOURLY_SNAPSHOT_SERVICE"
  echo "  $HOURLY_SNAPSHOT_TIMER"
  echo "  $INCIDENT_REPORTER_SERVICE"
  echo "  $INCIDENT_REPORTER_TIMER"
fi
