#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'USAGE'
Install the BlockDAG dashboard/watchdog as user-level systemd services.

Usage:
  ops/install-dashboard.sh [options]

Options:
  --name NAME          Service prefix. Default: bdag
  --bind ADDRESS      Dashboard bind address. Default: 127.0.0.1
  --port PORT         Dashboard port. Default: 8088
  --runtime-dir DIR   Runtime state/log directory. Default: ops/runtime
  --env-file FILE     Service environment file. Default: RUNTIME_DIR/ops.env
  --no-watchdog       Install only the dashboard service
  --no-sync-coordinator
                      Do not install the large-catch-up node sync coordinator
  --no-start          Write units but do not enable/start services
  -h, --help          Show this help

Examples:
  ops/install-dashboard.sh
  ops/install-dashboard.sh --name pool2 --port 8090 --runtime-dir /var/lib/bdag-pool2
USAGE
}

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
INSTANCE="bdag"
BIND="${BDAG_DASHBOARD_BIND:-127.0.0.1}"
PORT="${BDAG_DASHBOARD_PORT:-8088}"
RUNTIME_DIR="${BDAG_RUNTIME_DIR:-}"
ENV_FILE=""
INSTALL_WATCHDOG=1
INSTALL_SYNC_COORDINATOR=1
START_SERVICES=1
RUNTIME_SET=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    --name)
      INSTANCE="${2:?--name requires a value}"
      shift 2
      ;;
    --bind)
      BIND="${2:?--bind requires a value}"
      shift 2
      ;;
    --port)
      PORT="${2:?--port requires a value}"
      shift 2
      ;;
    --runtime-dir)
      RUNTIME_DIR="${2:?--runtime-dir requires a value}"
      RUNTIME_SET=1
      shift 2
      ;;
    --env-file)
      ENV_FILE="${2:?--env-file requires a value}"
      shift 2
      ;;
    --no-watchdog)
      INSTALL_WATCHDOG=0
      INSTALL_SYNC_COORDINATOR=0
      shift
      ;;
    --no-sync-coordinator)
      INSTALL_SYNC_COORDINATOR=0
      shift
      ;;
    --no-start)
      START_SERVICES=0
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown option: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

INSTANCE="$(printf '%s' "$INSTANCE" | tr -c 'A-Za-z0-9_.-' '-')"
if [[ -z "$INSTANCE" ]]; then
  INSTANCE="bdag"
fi

if [[ -z "$RUNTIME_DIR" ]]; then
  if [[ "$INSTANCE" == "bdag" || "$RUNTIME_SET" -eq 1 ]]; then
    RUNTIME_DIR="$PROJECT_ROOT/ops/runtime"
  else
    RUNTIME_DIR="$PROJECT_ROOT/ops/runtime-$INSTANCE"
  fi
fi
if [[ -z "$ENV_FILE" ]]; then
  ENV_FILE="$RUNTIME_DIR/ops.env"
fi

mkdir -p "$RUNTIME_DIR/logs" "$(dirname "$ENV_FILE")" "$HOME/.config/systemd/user"

if [[ ! -f "$ENV_FILE" ]]; then
  cat > "$ENV_FILE" <<EOF
# Generated by ops/install-dashboard.sh. Edit this file for this pool instance.
BDAG_PROJECT_ROOT=$PROJECT_ROOT
BDAG_RUNTIME_DIR=$RUNTIME_DIR
BDAG_POOL_ENV_FILE=$PROJECT_ROOT/asic-pool/.env
BDAG_DASHBOARD_BIND=$BIND
BDAG_DASHBOARD_PORT=$PORT
BDAG_DASHBOARD_REQUIRE_TOKEN=auto

BDAG_POOL_CONTAINER=asic-pool
BDAG_POOL_DB_CONTAINER=pool-db
BDAG_POOL_DB_USER=test
BDAG_POOL_DB_NAME=pool
BDAG_NODE_SERVICES=bdag-miner-node-1,bdag-miner-node-2
BDAG_STACK_SERVICES=pool-db,bdag-miner-node-1,bdag-miner-node-2,rpc-failover,asic-pool

# A backend node lagging the other by 1000 DAG main-order/block entries is a
# major operational fault. At that point the standby is no longer a reliable
# failover target and can feed stale templates if routing regresses.
BDAG_NODE_LAG_MAJOR_BLOCKS=1000
BDAG_SYNC_COORDINATOR_FAR_BEHIND_BLOCKS=1000
BDAG_SYNC_COORDINATOR_FOLLOWER_LAG_BLOCKS=1000
BDAG_SYNC_COORDINATOR_MAJOR_LAG_MAX_SECONDS=600

# Optional overrides:
# BDAG_MINING_ADDRESS=0x0000000000000000000000000000000000000000
# BDAG_POOL_HOST=192.168.1.10
# BDAG_POOL_URL=stratum+tcp://192.168.1.10:3334
# BDAG_MINER_SCAN_TARGET=192.168.1.0/24
# DOCKER_HOST=ssh://pool-admin@192.168.1.10
# CMC_PRO_API_KEY=
EOF
  chmod 0600 "$ENV_FILE"
fi

DASHBOARD_SERVICE="$HOME/.config/systemd/user/${INSTANCE}-dashboard.service"
WATCHDOG_SERVICE="$HOME/.config/systemd/user/${INSTANCE}-watchdog.service"
BOOT_REPAIR_SERVICE="$HOME/.config/systemd/user/${INSTANCE}-boot-repair.service"
SYNC_COORDINATOR_SERVICE="$HOME/.config/systemd/user/${INSTANCE}-sync-coordinator.service"
SYNC_COORDINATOR_TIMER="$HOME/.config/systemd/user/${INSTANCE}-sync-coordinator.timer"

cat > "$DASHBOARD_SERVICE" <<EOF
[Unit]
Description=BlockDAG pool operations dashboard ($INSTANCE)
After=${INSTANCE}-boot-repair.service default.target

[Service]
Type=simple
WorkingDirectory=$PROJECT_ROOT
Environment=BDAG_PROJECT_ROOT=$PROJECT_ROOT
Environment=BDAG_RUNTIME_DIR=$RUNTIME_DIR
Environment=BDAG_DASHBOARD_BIND=$BIND
Environment=BDAG_DASHBOARD_PORT=$PORT
EnvironmentFile=-$ENV_FILE
ExecStart=/usr/bin/env python3 $PROJECT_ROOT/ops/dashboard.py
Restart=always
RestartSec=5

[Install]
WantedBy=default.target
EOF

if [[ "$INSTALL_WATCHDOG" -eq 1 ]]; then
  cat > "$WATCHDOG_SERVICE" <<EOF
[Unit]
Description=BlockDAG pool watchdog and auto-repair worker ($INSTANCE)
After=${INSTANCE}-boot-repair.service default.target

[Service]
Type=simple
WorkingDirectory=$PROJECT_ROOT
Environment=BDAG_PROJECT_ROOT=$PROJECT_ROOT
Environment=BDAG_RUNTIME_DIR=$RUNTIME_DIR
Environment=BDAG_WATCHDOG_INTERVAL=30
Environment=BDAG_WATCHDOG_FAILURE_THRESHOLD=3
Environment=BDAG_CLEAN_RESTORE_COOLDOWN=1800
Environment=BDAG_ENABLE_AUTOMATIC_CLEAN_RESTORE=0
Environment=BDAG_BOOT_REPAIR_DIRTY_POLICY=start
Environment=BDAG_BOOT_REPAIR_CRITICAL_POLICY=restart
EnvironmentFile=-$ENV_FILE
ExecStartPre=/bin/sh -c 'i=0; while [ "\$i" -lt 60 ]; do docker info >/dev/null 2>&1 && exit 0; i=\$((i+1)); sleep 5; done; exit 1'
ExecStart=/usr/bin/env python3 $PROJECT_ROOT/ops/watchdog.py --loop
ExecStopPost=/bin/sh -c 'rm -f "\$BDAG_RUNTIME_DIR/dirty-shutdown.marker"'
Restart=always
RestartSec=10

[Install]
WantedBy=default.target
EOF
fi

if [[ "$INSTALL_SYNC_COORDINATOR" -eq 1 ]]; then
  cat > "$SYNC_COORDINATOR_SERVICE" <<EOF
[Unit]
Description=BlockDAG large catch-up sync coordinator ($INSTANCE)
After=default.target

[Service]
Type=oneshot
WorkingDirectory=$PROJECT_ROOT
Environment=BDAG_PROJECT_ROOT=$PROJECT_ROOT
Environment=BDAG_RUNTIME_DIR=$RUNTIME_DIR
Environment=BDAG_SYNC_COORDINATOR_FAR_BEHIND_BLOCKS=1000
Environment=BDAG_SYNC_COORDINATOR_FOLLOWER_LAG_BLOCKS=1000
Environment=BDAG_NODE_LAG_MAJOR_BLOCKS=1000
Environment=BDAG_SYNC_COORDINATOR_MAJOR_LAG_MAX_SECONDS=600
EnvironmentFile=-$ENV_FILE
Nice=10
IOSchedulingClass=best-effort
IOSchedulingPriority=7
CPUWeight=40
IOWeight=30
ExecStart=/usr/bin/env python3 $PROJECT_ROOT/ops/sync_coordinator.py --once --repair --pause-follower --resume-follower --restart-lagging-follower
EOF

  cat > "$SYNC_COORDINATOR_TIMER" <<EOF
[Unit]
Description=Run BlockDAG sync coordinator during large catch-up ($INSTANCE)

[Timer]
OnBootSec=3min
OnUnitActiveSec=2min
AccuracySec=30s
Persistent=true
Unit=${INSTANCE}-sync-coordinator.service

[Install]
WantedBy=timers.target
EOF
fi

if [[ "$INSTALL_WATCHDOG" -eq 1 ]]; then
  cat > "$BOOT_REPAIR_SERVICE" <<EOF
[Unit]
Description=BlockDAG pool boot-time recovery ($INSTANCE)
After=default.target

[Service]
Type=oneshot
WorkingDirectory=$PROJECT_ROOT
Environment=BDAG_PROJECT_ROOT=$PROJECT_ROOT
Environment=BDAG_RUNTIME_DIR=$RUNTIME_DIR
Environment=BDAG_WATCHDOG_INTERVAL=60
Environment=BDAG_WATCHDOG_FAILURE_THRESHOLD=3
Environment=BDAG_CLEAN_RESTORE_COOLDOWN=1800
Environment=BDAG_ENABLE_AUTOMATIC_CLEAN_RESTORE=0
Environment=BDAG_BOOT_REPAIR_DIRTY_POLICY=start
Environment=BDAG_BOOT_REPAIR_CRITICAL_POLICY=restart
EnvironmentFile=-$ENV_FILE
ExecStartPre=/bin/sh -c 'i=0; while [ "\$i" -lt 60 ]; do docker info >/dev/null 2>&1 && exit 0; i=\$((i+1)); sleep 5; done; exit 1'
ExecStart=/usr/bin/env python3 $PROJECT_ROOT/ops/watchdog.py --boot-repair

[Install]
WantedBy=default.target
EOF
fi

systemctl --user daemon-reload
if [[ "$START_SERVICES" -eq 1 ]]; then
  if [[ "$INSTALL_WATCHDOG" -eq 1 ]]; then
    systemctl --user enable --now "${INSTANCE}-boot-repair.service"
  fi
  systemctl --user enable --now "${INSTANCE}-dashboard.service"
  if [[ "$INSTALL_WATCHDOG" -eq 1 ]]; then
    systemctl --user enable --now "${INSTANCE}-watchdog.service"
  fi
  if [[ "$INSTALL_SYNC_COORDINATOR" -eq 1 ]]; then
    systemctl --user enable --now "${INSTANCE}-sync-coordinator.timer"
  fi
fi

cat <<EOF
Installed:
  $DASHBOARD_SERVICE
  $ENV_FILE

Dashboard:
  http://$BIND:$PORT

Edit the environment file for pool-specific container names, wallet address,
miner scan target, Docker remote host, and repair commands.
EOF
if [[ "$INSTALL_WATCHDOG" -eq 1 ]]; then
  echo "  $BOOT_REPAIR_SERVICE"
  echo "  $WATCHDOG_SERVICE"
fi
if [[ "$INSTALL_SYNC_COORDINATOR" -eq 1 ]]; then
  echo "  $SYNC_COORDINATOR_SERVICE"
  echo "  $SYNC_COORDINATOR_TIMER"
fi
